---
# Cloudera playbook
- name: Install ntp
  hosts: all
  roles:
    - ntp
  tags: ntp

- name: Install Cloudera Manager Server
  hosts: scm_server
  roles:
    - scm
  tags: cluster_template

- name: Install CDH
  hosts: scm_server
  roles:
    - cdh
  tags: cluster_template

