---
# https://cloudera.github.io/cm_api/docs/python-client/

- name: Install Python PIP
  yum: 
    name: python-pip
    state: latest
    update_cache: yes
  delegate_to: localhost

- name: Install CM Python API Client
  pip: 
    name: cm-api
    state: present
  delegate_to: localhost


